### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by stuart-thackray** [umbrellary/piweb#1]
Hi,

The make file is failing 

mvn package
make: mvn: Command not found
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 127

I have tried to install maven (but currently getting failure to install it)

Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main tzdata-java all 2015f-0+deb7u1
  404  Not Found
Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main bsh all 2.0b4-12
  404  Not Found
Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main bsh-gcj armhf 2.0b4-12
  404  Not Found
Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main libservlet2.5-java all 6.0.35-6+deb7u1
  404  Not Found
Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main libcommons-httpclient-java all 3.1-10.2+deb7u1
  404  Not Found
Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main libmaven2-core-java all 2.2.1-8
  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/t/tzdata/tzdata-java_2015f-0+deb7u1_all.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/b/bsh/bsh_2.0b4-12_all.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/b/bsh/bsh-gcj_2.0b4-12_armhf.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/t/tomcat6/libservlet2.5-java_6.0.35-6+deb7u1_all.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/c/commons-httpclient/libcommons-httpclient-java_3.1-10.2+deb7u1_all.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/m/maven2-core/libmaven2-core-java_2.2.1-8_all.deb  404  Not Found
Unable to correct missing packages.
E: Aborting install.

Is this the prerequisite you need to install for it to work? Or is there another package for raspberrypi 4.1.13-v7+?

I have written something similar fyi (https://github.com/stuart-thackray/pi_gpio_web) But yours looks a lot better keen to try it.

**Comment by umbrellary** [comment]
Hello 


thanks your reply!
You should first execute the command: 'sudo apt-get update’.
Then install the maven.




Best wishes







Harry
rui.crater@gmail.com | http://www.umbrellary.com | Skype: rui.crater@outlook.com | 中国 苏州
   


发件人:  stuart-thackray <notifications@github.com>
答复:  umbrellary/piweb <reply@reply.github.com>
日期:  2016年5月4日 星期三 上午1:53
至:  umbrellary/piweb <piweb@noreply.github.com>
主题:  [umbrellary/piweb] make failed (#1)


Hi,

The make file is failing 

mvn package
make: mvn: Command not found
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 127

I have tried to install maven (but currently getting failure to install it)

Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main tzdata-java all 2015f-0+deb7u1
 404  Not Found
Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main bsh all 2.0b4-12
 404  Not Found
Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main bsh-gcj armhf 2.0b4-12
 404  Not Found
Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main libservlet2.5-java all 6.0.35-6+deb7u1
 404  Not Found
Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main libcommons-httpclient-java all 3.1-10.2+deb7u1
 404  Not Found
Err http://mirrordirector.raspbian.org/raspbian/ wheezy/main libmaven2-core-java all 2.2.1-8
 404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/t/tzdata/tzdata-java_2015f-0+deb7u1_all.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/b/bsh/bsh_2.0b4-12_all.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/b/bsh/bsh-gcj_2.0b4-12_armhf.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/t/tomcat6/libservlet2.5-java_6.0.35-6+deb7u1_all.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/c/commons-httpclient/libcommons-httpclient-java_3.1-10.2+deb7u1_all.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/m/maven2-core/libmaven2-core-java_2.2.1-8_all.deb  404  Not Found
Unable to correct missing packages.
E: Aborting install.

Is this the prerequisite you need to install for it to work? Or is there another package for raspberrypi 4.1.13-v7+?

I have written something similar fyi (https://github.com/stuart-thackray/pi_gpio_web) But yours looks a lot better keen to try it.

**Comment by stuart-thackray** [comment]
Thanks I forgot the SD drive I was using was not updated recently will give that a go;  when I get a chance. 

I would suggest you possibly add that to the readme the perquisites required.

**Comment by umbrellary** [comment]
ok..I have added.





Harry
rui.crater@gmail.com | http://www.umbrellary.com | Skype: rui.crater@outlook.com | 中国 苏州
   


发件人:  stuart-thackray <notifications@github.com>
答复:  umbrellary/piweb <reply@reply.github.com>
日期:  2016年5月4日 星期三 下午3:40
至:  umbrellary/piweb <piweb@noreply.github.com>
抄送:  Harry <rui.crater@gmail.com>, Comment <comment@noreply.github.com>
主题:  Re: [umbrellary/piweb] make failed (#1)


Thanks I forgot the SD drive I was using was not updated recently will give that a go;  when I get a chance. 

I would suggest you possibly add that to the readme the perquisites required.
